name: Deployment

on:
  push:
    branches:
      - master
  
  pull_request:
    branches: 
      - master
      
  workflow_dispatch:  
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Installing dependencies
        run: npm ci
        
      - name: Running tests
        run: npm test
  
  deploy:
    if: ${{ github.event_name }} == 'push'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Compressing project files
        run: zip -r dist.zip ./ 
        
      - name: Deploy project via SCP
        uses: siva1024/scp-deployer@v1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: dist.zip
          target: ~/dist.zip
        
      - name: Connecting to server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/
            rm -rf app && mkdir app
            mv dist.zip app/ && cd app
            unzip dist.zip
            npm ci
            npm run build
            npm run start:prod
